export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const CLEAR_CART = 'CLEAR_CART';
export const LOGOUT_USER = 'LOGOUT_USER';


